# Generated by Django 5.1.2 on 2024-10-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_desc', models.TextField()),
                ('brand_logo', models.ImageField(upload_to='brand/')),
                ('brand_slug', models.SlugField(unique=True)),
                ('brand_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_id', models.BigIntegerField(null=True)),
                ('cat_title', models.TextField()),
                ('cat_desc', models.CharField(max_length=800)),
                ('cat_slug', models.SlugField(unique=True)),
                ('cat_status', models.BooleanField(default=False)),
            ],
        ),
    ]
