# Generated by Django 5.1.2 on 2024-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_cat_desc_alter_category_cat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_status',
            field=models.BooleanField(default=True),
        ),
    ]
