# Generated by Django 5.1.2 on 2024-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_brand_brand_status_alter_category_cat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_status',
            field=models.BooleanField(default=False),
        ),
    ]
