# Generated by Django 5.1.2 on 2024-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='DEFAULT-SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='image',
            field=models.ImageField(default='productVariant/default.jpg', upload_to='productVariant/'),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='variant_name',
            field=models.CharField(default='Default Variant', max_length=200),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='variant_type',
            field=models.CharField(default='Standard', max_length=200),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='sku',
            field=models.CharField(default='DEFAULT-SKU', max_length=100),
        ),
    ]
