# Generated by Django 5.1.2 on 2024-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('mg', 'Milligram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('l', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen'), ('pcs', 'Pieces'), ('bundle', 'Bundle'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('bag', 'Bag')], default='g', max_length=10),
        ),
    ]
